name: LLM Code Scan

on:
  pull_request:
    types: [closed]
    branches:
      - main  # Adjust this to match the branch you want to protect
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-scan:
    runs-on: [self-hosted, Linux, X64, zap]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB }}
    steps:
      - name: Checkout current repo (target)
        uses: actions/checkout@v3
      - name: Zap-scan
        run: python3 Scripts/Zap-scan.py
      - name: PR creation
        run: python3 Scripts/Createpr.py
 
