name: LLM Code Scan

on:
  pull_request:
    branches:
      - main  # Adjust this to match the branch you want to protect
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-scan:
    runs-on: [self-hosted, Linux, X64, zap]
    steps:
      - name: llm
        run: echo "new"
 
